# Generated by Django 2.2.13 on 2020-06-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='(placeholder for the body of the blog)'),
            preserve_default=False,
        ),
    ]
